version: "3"
services:
  osa_expert_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${BOT_VOLUME_PATH}:/osa_expert_bot/
    env_file: # Указываем явно путь к файлу с переменными окружения
      - .env
    restart: always